version: "3.5"

services:
  polkadot:
    image: polkadot:${IMAGE_TAG__POLKADOT:-latest}
    volumes:
      - ~/.polkadot:/root/.polkadot
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - "9933:9933"
      - "9944:9944"
