version: "3.5"

services:
  bitcoind:
    image: bitcoincash:${IMAGE_TAG__BITCOINCASH:-latest}
    volumes:
      - ~/.bitcoin:/root/.bitcoin
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - "8332:8332"
      - "8333:8333"
