version: "3.5"

services:
  geth:
    image: geth:${IMAGE_TAG__GETH:-latest}
    volumes:
      - ~/.ethereum/geth:/root/.ethereum/geth
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - "8545:8545"
      - "30303:30303"
