version: "3.5"

services:
  qtumd:
    image: qtum:${IMAGE_TAG__QTUM:-latest}
    volumes:
      - ~/.qtum:/root/.qtum
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - "3888:3888"
      - "3889:3889"
